### PR TITLE
45 save retrofit strategy query parameters

### PR DESCRIPTION
**Pull request by longshuicy**
- GET /maestro/{testbed}/datasets/{incore_dataset_id}/rsdetails
- POST /maestro/{testbed}/datasets/{incore_dataset_id}/rsdetails
payload
```
{
        "total": {
            "num_bldg": 3283,
            "num_bldg_no_cost": 42,
            "cost": 117260721.43
        },
        "by_rule": {
            "0": {
                "num_bldg": 3191,
                "num_bldg_no_cost": 40,
                "cost": 94393478.73
            },
            "1": {
                "num_bldg": 90,
                "num_bldg_no_cost": 0,
                "cost": 22867242.7
            },
            "2": {
                "num_bldg": 2,
                "num_bldg_no_cost": 2,
                "cost": 0
            }
        },
        "rules": {
            "testbed": "galveston",
            "rules": 3,
            "zones": ["1P", "1P", "0.2P"],
            "strtypes": ["1", "2", "1"],
            "pcts": [1, 1, 1]
        },
        "retrofits": {
            "ret_keys": ["elevation", "elevation", "elevation"],
            "ret_vals": [5, 10, 5]
        },
        "rsDetailsLayerId": "dummy_layer_id"
    }
```
- DELETE /maestro/{testbed}/datasets/{incore_dataset_id}/rsdetails

----

Test **locally** by running pytest `app/tests/test_retrofit_strategies.py`
Also explore the swagger api at: http://localhost:8000/docs#/datasets

### CODE REVIEW

**Comment by ylyangtw** [comment]
I refer to the test for parameters but only get `"detail": "retrofit strategy details not found"}`
image
Am I using the correct dataset id?

**Comment by longshuicy** [comment]
> I refer to the test for parameters but only get `"detail": "retrofit strategy details not found"}` image Am I using the correct dataset id?

Oh i might accidently deleted that dataset. Could you try this id "65fb5320e42f3b0da565d1dc" instead?

**Review by ylyangtw — APPROVED** [review]
tested the services, all work well

**Comment by Rashmil-1999** [comment]
Yes, I've integrated the service in the PR so it works well

**Review by Rashmil-1999 — APPROVED** [review]

**Pull request merged**
