### PR TITLE
20 record the last person who updated the status

### PR DESCRIPTION
**Pull request by Rashmil-1999**
This PR modifies the following functionality:
-  Add a user on the step model to keep track of who edited the step recently with a timestamp.
-  Modify the Role creation endpoint and Step update endpoint to use Header dependency in FastAPI.
-  Swagger updates.

To test this PR you must drop Step, Role, and their respective enums so that we can have new enum values.
-  `DROP TABLE steps;`
-  `DROP TABLE userroles;`
-  You might have to drop the user's table too `DROP TABLE users;`
-  `DROP TYPE _status_enum;`

### CODE REVIEW

**Comment by Rashmil-1999** [comment]
This PR uses @longshuicy 's changes too. I hope it covers everything.

**Comment by longshuicy** [comment]
I got an error creating a step first, for some reason it is not recognizing the enum step?
image

**Comment by Rashmil-1999** [comment]
Yes, you need to drop the existing enum type since there is a change in the way the enum is defined now.

**Comment by Rashmil-1999** [comment]
This same might happen with Roles

**Comment by Rashmil-1999** [comment]
> This PR modifies the following functionality:
> 
> * Add a user on the step model to keep track of who edited the step recently with a timestamp.
> * Modify the Role creation endpoint and Step update endpoint to use Header dependency in FastAPI.
> * Swagger updates.
> 
> To test this PR you must drop Step, Role, and their respective enums so that we can have new enum values.
> 
> * `DROP TABLE steps;`
> * `DROP TABLE userroles;`
> * You might have to drop the user's table too `DROP TABLE users;`
> * `DROP TYPE _status_enum;`

You can refer to the last point. Doing this will make things work better.

**Review by longshuicy — APPROVED** [review]
works for me now. Approving

**Pull request merged**
